# Generated by Django 3.2.2 on 2021-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Book_type',
            field=models.CharField(choices=[('sports', 'sports'), ('educational', 'educational'), ('motivational', 'motivational')], default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='Category',
            field=models.CharField(choices=[('Ebook', 'Ebook'), ('Hardcopy', 'Hardcopy')], default=1, max_length=100),
        ),
    ]
