# Generated by Django 3.2.2 on 2021-05-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20210510_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Price',
            field=models.CharField(max_length=50),
        ),
    ]
