# Generated by Django 3.1.7 on 2021-09-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Cover_page_img',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
